### ISSUE TITLE
Error when loading on paper 1.16.5

### ISSUE THREAD

**Issue by NTLTC** [andrei923/LeafSK#11]
Hi, I'm getting this error when trying to start the plugin, I use it with my LeafBridge plugin that I bought on your mc-market, and I really need that plugin to load if I want to use the leafbridge plugin...

`[12:27:47 ERROR]: Could not load 'plugins/LeafSK.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-782]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-782]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Paper-782]
        ... 7 more
Caused by: java.lang.ClassCastException: class io.puharesource.mc.titlemanager.TitleManagerPlugin cannot be cast to class io.puharesource.mc.titlemanager.api.v2.TitleManagerAPI (io.puharesource.mc.titlemanager.TitleManagerPlugin is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @57a5a4f9; io.puharesource.mc.titlemanager.api.v2.TitleManagerAPI is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @170b39c1)
        at com.leaf.Leaf.<clinit>(Leaf.java:46) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:466) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82) ~[patched_1.16.5.jar:git-Paper-782]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.16.5.jar:git-Paper-782]
        ... 7 more`

**Comment by Fr4Ckt3r** [comment]
same, i use spigot tho
